title: Saarthak Jain
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > 
 Actively Seeking New Grad'23/SDE roles | MS CS @ ASU
  <br><br>
  <a href="mailto:jain-saarthak@outlook.com">jain-saarthak@outlook.com</a>
  <br>
  <a href="https://www.linkedin.com/in/jain-saarthak/">LinkedIn</a>
  <br>
  <a href="https://github.com/jain-saarthak">Gihub</a> 
theme: jekyll-theme-minimal
